In [5]:

a=[]
size=int(input("enter the size"))
for i in range(size):
 val=int(input("enter the value"))
 a.append(val)
print(a)
b=np.array(a)
b

enter the size4
enter the value1
enter the value2
enter the value3
enter the value4
[1, 2, 3, 4]


array([1, 2, 3, 4])

In [7]:
# how to check size and dimension of an array
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("total dimension",b.ndim)
print("shape of an array",b.shape)

total dimension 2
shape of an array (3, 3)


In [11]:
# Zeros==>this function create an array (either one dimensional or multi dimensional )and filled the value with zeros
import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [12]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# ones==>this function create an array (either one dimensional or multi dimensional )and filled the value with ones
import numpy as np
a=np.ones(5)
a


array([1., 1., 1., 1., 1.])

In [14]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# EYE==>this function creats an array with all the digonal element as 1 and rest are 0( in square matrix).in non square matrix the value are still one for digonal (upto which it can draw digonal)and rest are zero
import numpy as np
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# diag==>this function create a two dimensional array with all the dignal element as the given value and rest are zero
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [18]:
# randit==>this function is used to generate a random number between a given range
# syntax==randint(min_value,max_value,total_numbers)
import numpy as np
a=np.random.randint(1,44,6)
a

array([30, 18, 20, 17, 41, 40])

In [19]:
# rand==>this function is used to generate a random number btw o to 1
# syntax==rand(numberofvalues)
import numpy as np
a=np.random.rand(5)
a

array([0.68382913, 0.82141909, 0.91221677, 0.28630532, 0.76081007])

In [20]:
# randn==>this function is used to generate a random number from -3 to 3 . this may return positive or negative numbers as well
import numpy as np
a=np.random.randn(5)
a

array([ 1.27669893,  0.61279493, -0.81881108,  0.82291602, -1.57775566])

In [22]:
# reshaping data
import numpy as np
a=np.random.randint(1,50,12)
a

array([36,  1, 15, 40, 49,  5, 25, 12, 48, 45,  1, 41])

In [23]:
a.shape

(12,)

In [24]:
a=a.reshape(2,6)
a

array([[36,  1, 15, 40, 49,  5],
       [25, 12, 48, 45,  1, 41]])

In [25]:
a=a.reshape(6,2)
a

array([[36,  1],
       [15, 40],
       [49,  5],
       [25, 12],
       [48, 45],
       [ 1, 41]])

In [26]:
a=a.reshape(4,3)
a

array([[36,  1, 15],
       [40, 49,  5],
       [25, 12, 48],
       [45,  1, 41]])

In [27]:
a=a.reshape(3,4)
a

array([[36,  1, 15, 40],
       [49,  5, 25, 12],
       [48, 45,  1, 41]])

In [29]:
a=a.reshape(6,2)
a

array([[36,  1],
       [15, 40],
       [49,  5],
       [25, 12],
       [48, 45],
       [ 1, 41]])

In [43]:
import numpy as np
a=np.random.randint(1,100,36)
a

array([19, 32, 71, 75, 78, 79, 81, 32, 30, 40, 14, 64, 98, 84, 64, 37, 44,
       88,  5, 78, 41, 50, 62,  3, 78, 68,  5, 74, 39, 73, 77, 96, 36, 29,
       13, 24])

In [31]:
a.shape

(36,)

In [33]:
a=a.reshape(6,6)
a

array([[71, 46, 88, 92, 90, 55],
       [50, 79, 84,  5, 59, 76],
       [97, 80, 21, 70, 24, 71],
       [72, 42, 14, 50, 55, 42],
       [10, 82, 78, 22, 44, 32],
       [93, 65, 26, 89, 31, 53]])

In [37]:
a=a.reshape(3,12)
a


array([[71, 46, 88, 92, 90, 55, 50, 79, 84,  5, 59, 76],
       [97, 80, 21, 70, 24, 71, 72, 42, 14, 50, 55, 42],
       [10, 82, 78, 22, 44, 32, 93, 65, 26, 89, 31, 53]])

In [39]:
a=a.reshape(12,3)
a

array([[71, 46, 88],
       [92, 90, 55],
       [50, 79, 84],
       [ 5, 59, 76],
       [97, 80, 21],
       [70, 24, 71],
       [72, 42, 14],
       [50, 55, 42],
       [10, 82, 78],
       [22, 44, 32],
       [93, 65, 26],
       [89, 31, 53]])

In [42]:
a=a.reshape(2,18)
a


array([[71, 46, 88, 92, 90, 55, 50, 79, 84,  5, 59, 76, 97, 80, 21, 70,
        24, 71],
       [72, 42, 14, 50, 55, 42, 10, 82, 78, 22, 44, 32, 93, 65, 26, 89,
        31, 53]])

In [53]:
# seed function()==>we know that randit function generate random numbers . everytime we run the programe we will use seed function.
import numpy as np
np.random.seed(5555)
a=np.random.randint(1,100,10)
a

array([75, 13, 30, 67, 91, 95, 60, 81, 81, 77])

In [4]:
# vieaw
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a



array([10, 20, 30,  0,  0,  0, 70, 80])

In [5]:
# conditional selection
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [7]:
a<10


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [9]:
b=a>10
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [10]:
a[a%2==0]


array([ 2,  4,  6,  8, 10, 12, 14])

In [11]:
# opretions on array
a=np.arange(1,5)
a*2      

array([2, 4, 6, 8])

In [12]:
a+2

array([3, 4, 5, 6])

In [13]:
a**2

array([ 1,  4,  9, 16])

In [15]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [16]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [17]:
a+b

array([[ 6,  8],
       [10, 12]])

In [18]:
a-b

array([[-4, -4],
       [-4, -4]])

In [19]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [20]:
a*b

array([[ 5, 12],
       [21, 32]])

In [21]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [25]:
a=np.array([10,20,30,40,50,60,70,80])
np.min(a)

10

In [26]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669, 8.36660027, 8.94427191])

In [27]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062,  0.77389068, -0.99388865])

In [30]:
# linespace
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [2]:
import numpy as np
import random
np.random.seed(1)
a=random.randint(1,21,9).reshape(3,3)

TypeError: Random.randint() takes 3 positional arguments but 4 were given

In [36]:
# np.unique(arr,return_index=true_count=true)
# returns3arrays 1. the array with uniqe values 2. the array whith respective index value 3. the array whith countiing of frequancy
a=np.array([10,20,30,40,10,20,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [37]:
# horizontal and verticle
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [38]:
b


array([5, 6, 7, 8])

In [39]:
np.hstack((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# 1:write a statment to import numpy
# 2:create an array using nummy    
# 3:create an aarray of 10 random integers?    
# 4:create an array of elelment from 10-20?
# 5:create an array which contain value 5,10 times?
# 6:create a one dimensional array and convert that into 3*3 matrix?
# 7:create a 2d array of size 3*3 but all the element should be btw 0 to 1?
# 8:concatenate 2d array horizontally and vertically    

In [60]:
import numpy as np

arra=np.array([1,2,3,4,5,6,7])
arra


array([1, 2, 3, 4, 5, 6, 7])

In [7]:
import numpy as np
a = np.random.randint(1,101,10)
print(a)


[28  6 76 89 95 76 85 80 25 77]


In [44]:

b = np.arange(10, 21)
print(b)


[10 11 12 13 14 15 16 17 18 19 20]


In [45]:

c = np.full(10, 5)
print(c)


[5 5 5 5 5 5 5 5 5 5]


In [46]:

one_dim_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

d = one_dim_array.reshape(3, 3)
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:

e = np.random.rand(3, 3)
print(e)


[[0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262]]


In [49]:

array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                    [10, 11, 12]])


array1+array2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [50]:
np.hstack((array1,array2))


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
np.vstack((array1,array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])